name: arcgispro-cems
channels:
  - esri
  - conda-forge
dependencies:         # everything under this, installed by conda
  - python=3.9
  - arcpy=3.0
  - pyyaml # workaround
  - jinja2=3.0.3 # workaround https://github.com/d2l-ai/d2l-book/issues/46
  - gdal>=3.5
  - rasterio>=1.3.0
  - geopandas>=0.11.0
  - pip
  - pip:                # everything under this, installed by pip
      - -r ./requirements.txt